[language-server.rust-analyzer.config.cargo]
allTargets = false
noDefaultFeatures = true
target = "thumbv7em-none-eabihf"

[language-server.rust-analyzer.config.check]
allTargets = false
noDefaultFeatures = true
target = "thumbv7em-none-eabihf"
