[build]
target = "thumbv7em-none-eabihf"
[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip STM32G431CBUx"
rustflags = [
    "-C", "linker=flip-link",
    "-C", "link-arg=-Tdefmt.x",
    "-C", "link-arg=-Tlink.x",
    # "-C", "link-arg=--nmagic",
]
